/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_appleHalf: THREE.Mesh
    Mesh_appleHalf_1: THREE.Mesh
    Mesh_appleHalf_2: THREE.Mesh
    Mesh_appleHalf_3: THREE.Mesh
    Mesh_appleHalf_4: THREE.Mesh
  }
  materials: {
    red: THREE.MeshStandardMaterial
    brown: THREE.MeshStandardMaterial
    brownLight: THREE.MeshStandardMaterial
    brownDark: THREE.MeshStandardMaterial
    _defaultMat: THREE.MeshStandardMaterial
  }
}

export function AppleHalf({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/appleHalf.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_appleHalf.geometry} material={materials.red} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_appleHalf_1.geometry} material={materials.brown} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_appleHalf_2.geometry} material={materials.brownLight} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_appleHalf_3.geometry} material={materials.brownDark} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_appleHalf_4.geometry} material={materials._defaultMat} />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/appleHalf.glb')
