/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_avocadoHalf: THREE.Mesh
    Mesh_avocadoHalf_1: THREE.Mesh
    Mesh_avocadoHalf_2: THREE.Mesh
    pit: THREE.Mesh
  }
  materials: {
    green: THREE.MeshStandardMaterial
    brownDarkest: THREE.MeshStandardMaterial
    brownDark: THREE.MeshStandardMaterial
  }
}

export function AvocadoHalf({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/avocadoHalf.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.53}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh_avocadoHalf.geometry} material={materials.green} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_avocadoHalf_1.geometry} material={materials.brownDarkest} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_avocadoHalf_2.geometry}
          material={nodes.Mesh_avocadoHalf_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pit.geometry}
          material={nodes.pit.material}
          position={[0, 0.16, 0]}
          scale={0.38}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/avocadoHalf.glb')
