/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_beet: THREE.Mesh
    Mesh_beet_1: THREE.Mesh
    Mesh_beet_2: THREE.Mesh
  }
  materials: {
    purpleLight: THREE.MeshStandardMaterial
    _defaultMat: THREE.MeshStandardMaterial
    green: THREE.MeshStandardMaterial
  }
}

export function Beet({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/beet.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_beet.geometry} material={materials.purpleLight} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_beet_1.geometry} material={materials._defaultMat} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_beet_2.geometry} material={materials.green} />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/beet.glb')
