/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_bowlCereal: THREE.Mesh
    Mesh_bowlCereal_1: THREE.Mesh
    Mesh_bowlCereal_2: THREE.Mesh
    Mesh_bowlCereal_3: THREE.Mesh
    Mesh_bowlCereal_4: THREE.Mesh
  }
  materials: {
    greyLight: THREE.MeshStandardMaterial
    green: THREE.MeshStandardMaterial
    _defaultMat: THREE.MeshStandardMaterial
    yellow: THREE.MeshStandardMaterial
    pink: THREE.MeshStandardMaterial
  }
}

export function BowlCereal({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/bowlCereal.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_bowlCereal.geometry} material={materials.greyLight} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_bowlCereal_1.geometry} material={materials.green} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_bowlCereal_2.geometry} material={materials._defaultMat} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_bowlCereal_3.geometry} material={materials.yellow} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_bowlCereal_4.geometry} material={materials.pink} />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/bowlCereal.glb')
