/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_broccoli: THREE.Mesh
    Mesh_broccoli_1: THREE.Mesh
  }
  materials: {
    greenDark: THREE.MeshStandardMaterial
    green: THREE.MeshStandardMaterial
  }
}

export function Broccoli({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/broccoli.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_broccoli.geometry} material={materials.greenDark} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_broccoli_1.geometry} material={materials.green} />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/broccoli.glb')
