/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    bunBottom: THREE.Mesh
    bunBottom_1: THREE.Mesh
    bunTop: THREE.Mesh
    cheese: THREE.Mesh
    cheese_1: THREE.Mesh
    patty: THREE.Mesh
    patty_1: THREE.Mesh
  }
  materials: {
    brownLight: THREE.MeshStandardMaterial
    yellow: THREE.MeshStandardMaterial
    brownDark: THREE.MeshStandardMaterial
  }
}

export function BurgerCheeseDouble({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/burgerCheeseDouble.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.bunBottom.geometry} material={nodes.bunBottom.material} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bunBottom_1.geometry}
        material={nodes.bunBottom_1.material}
        position={[0, 0.1, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bunTop.geometry}
        material={nodes.bunTop.material}
        position={[0, 0.2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cheese.geometry}
        material={nodes.cheese.material}
        position={[0, 0.06, 0]}
        scale={[2.79, 1, 1.43]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cheese_1.geometry}
        material={nodes.cheese_1.material}
        position={[0, 0.16, 0]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[2.79, 1, 1.43]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.patty.geometry}
        material={nodes.patty.material}
        position={[0, 0.04, 0]}
        scale={[1, 1.14, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.patty_1.geometry}
        material={nodes.patty_1.material}
        position={[0, 0.14, 0]}
        scale={[1, 1.14, 1]}
      />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/burgerCheeseDouble.glb')
