/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    bunBottom: THREE.Mesh
    bunTop: THREE.Mesh
    cheese: THREE.Mesh
    patty: THREE.Mesh
    salad: THREE.Mesh
    Mesh_tomato: THREE.Mesh
    Mesh_tomato_1: THREE.Mesh
  }
  materials: {
    brownLight: THREE.MeshStandardMaterial
    yellow: THREE.MeshStandardMaterial
    brownDark: THREE.MeshStandardMaterial
    green: THREE.MeshStandardMaterial
    _defaultMat: THREE.MeshStandardMaterial
    red: THREE.MeshStandardMaterial
  }
}

export function Burger({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/burger.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.bunBottom.geometry} material={nodes.bunBottom.material} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bunTop.geometry}
        material={nodes.bunTop.material}
        position={[0, 0.17, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cheese.geometry}
        material={materials.yellow}
        position={[0, 0.09, 0]}
        scale={[2.79, 1, 1.43]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.patty.geometry}
        material={materials.brownDark}
        position={[0, 0.07, 0]}
        scale={[1, 1.14, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.salad.geometry}
        material={materials.green}
        position={[0, 0.04, 0]}
        scale={[0.92, 0.75, 0.92]}
      />
      <group position={[0, 0.14, 0]} scale={[1.56, 0.7, 1.56]}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh_tomato.geometry} material={materials._defaultMat} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_tomato_1.geometry} material={materials.red} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/burger.glb')
