/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_can: THREE.Mesh
    Mesh_can_1: THREE.Mesh
    Mesh_can_2: THREE.Mesh
  }
  materials: {
    greyLight: THREE.MeshStandardMaterial
    red: THREE.MeshStandardMaterial
    greyDark: THREE.MeshStandardMaterial
  }
}

export function Can({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/can.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_can.geometry} material={materials.greyLight} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_can_1.geometry} material={materials.red} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_can_2.geometry} material={materials.greyDark} />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/can.glb')
