/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_candyBarWrapper: THREE.Mesh
    Mesh_candyBarWrapper_1: THREE.Mesh
    Mesh_candyBarWrapper_2: THREE.Mesh
  }
  materials: {
    red: THREE.MeshStandardMaterial
    brownDark: THREE.MeshStandardMaterial
    white: THREE.MeshStandardMaterial
  }
}

export function CandyBarWrapper({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/candyBarWrapper.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_candyBarWrapper.geometry} material={materials.red} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_candyBarWrapper_1.geometry} material={materials.brownDark} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_candyBarWrapper_2.geometry} material={materials.white} />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/candyBarWrapper.glb')
