/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_carrot: THREE.Mesh
    Mesh_carrot_1: THREE.Mesh
  }
  materials: {
    orange: THREE.MeshStandardMaterial
    green: THREE.MeshStandardMaterial
  }
}

export function Carrot({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/carrot.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_carrot.geometry} material={materials.orange} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_carrot_1.geometry} material={materials.green} />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/carrot.glb')
