/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_carton: THREE.Mesh
    Mesh_carton_1: THREE.Mesh
    Mesh_carton_2: THREE.Mesh
  }
  materials: {
    purple: THREE.MeshStandardMaterial
    _defaultMat: THREE.MeshStandardMaterial
    white: THREE.MeshStandardMaterial
  }
}

export function Carton({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/carton.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_carton.geometry} material={materials.purple} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_carton_1.geometry} material={materials._defaultMat} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_carton_2.geometry} material={materials.white} />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/carton.glb')
