/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_cartonSmall: THREE.Mesh
    Mesh_cartonSmall_1: THREE.Mesh
    Mesh_cartonSmall_2: THREE.Mesh
  }
  materials: {
    _defaultMat: THREE.MeshStandardMaterial
    purpleLight: THREE.MeshStandardMaterial
    white: THREE.MeshStandardMaterial
  }
}

export function CartonSmall({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/cartonSmall.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_cartonSmall.geometry} material={materials._defaultMat} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_cartonSmall_1.geometry} material={materials.purpleLight} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_cartonSmall_2.geometry} material={materials.white} />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/cartonSmall.glb')
