/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_chocolateWrapper: THREE.Mesh
    Mesh_chocolateWrapper_1: THREE.Mesh
    Mesh_chocolateWrapper_2: THREE.Mesh
  }
  materials: {
    white: THREE.MeshStandardMaterial
    brownDark: THREE.MeshStandardMaterial
    purple: THREE.MeshStandardMaterial
  }
}

export function ChocolateWrapper({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/chocolateWrapper.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_chocolateWrapper.geometry} material={materials.white} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_chocolateWrapper_1.geometry} material={materials.brownDark} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_chocolateWrapper_2.geometry} material={materials.purple} />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/chocolateWrapper.glb')
