/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_coconutHalf: THREE.Mesh
    Mesh_coconutHalf_1: THREE.Mesh
  }
  materials: {
    brownDark: THREE.MeshStandardMaterial
    _defaultMat: THREE.MeshStandardMaterial
  }
}

export function CoconutHalf({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/coconutHalf.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[1.46, 1.75, 1.46]}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh_coconutHalf.geometry} material={materials.brownDark} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_coconutHalf_1.geometry} material={materials._defaultMat} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/coconutHalf.glb')
