/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_cookieChocolate: THREE.Mesh
    Mesh_cookieChocolate_1: THREE.Mesh
  }
  materials: {
    brownDarkest: THREE.MeshStandardMaterial
    _defaultMat: THREE.MeshStandardMaterial
  }
}

export function CookieChocolate({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/cookieChocolate.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_cookieChocolate.geometry} material={materials.brownDarkest} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_cookieChocolate_1.geometry}
        material={materials._defaultMat}
      />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/cookieChocolate.glb')
