/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_cookingKnifeChopping: THREE.Mesh
    Mesh_cookingKnifeChopping_1: THREE.Mesh
    Mesh_cookingKnifeChopping_2: THREE.Mesh
  }
  materials: {
    brownDarkest: THREE.MeshStandardMaterial
    greyLight: THREE.MeshStandardMaterial
    white: THREE.MeshStandardMaterial
  }
}

export function CookingKnifeChopping({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/cookingKnifeChopping.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_cookingKnifeChopping.geometry}
        material={materials.brownDarkest}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_cookingKnifeChopping_1.geometry}
        material={materials.greyLight}
      />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_cookingKnifeChopping_2.geometry} material={materials.white} />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/cookingKnifeChopping.glb')
