/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_fish: THREE.Mesh
    Mesh_fish_1: THREE.Mesh
    Mesh_fish_2: THREE.Mesh
  }
  materials: {
    pink: THREE.MeshStandardMaterial
    greyLight: THREE.MeshStandardMaterial
    _defaultMat: THREE.MeshStandardMaterial
  }
}

export function Fish({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/fish.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_fish.geometry} material={materials.pink} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_fish_1.geometry} material={materials.greyLight} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_fish_2.geometry} material={materials._defaultMat} />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/fish.glb')
