/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    fishBones: THREE.Mesh
  }
  materials: {
    greyLight: THREE.MeshStandardMaterial
  }
}

export function FishBones({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/fishBones.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.fishBones.geometry} material={materials.greyLight} />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/fishBones.glb')
