/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_frappe: THREE.Mesh
    Mesh_frappe_1: THREE.Mesh
    Mesh_frappe_2: THREE.Mesh
    straw: THREE.Mesh
  }
  materials: {
    brownDark: THREE.MeshStandardMaterial
    _defaultMat: THREE.MeshStandardMaterial
    brownLight: THREE.MeshStandardMaterial
    brownDarkest: THREE.MeshStandardMaterial
  }
}

export function Frappe({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/frappe.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_frappe.geometry} material={materials.brownDark} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_frappe_1.geometry} material={materials._defaultMat} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_frappe_2.geometry} material={materials.brownLight} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.straw.geometry}
        material={materials.brownDarkest}
        position={[0, 0.4, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/frappe.glb')
