/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    fries: THREE.Mesh
    fries_1: THREE.Mesh
  }
  materials: {
    red: THREE.MeshStandardMaterial
    yellow: THREE.MeshStandardMaterial
  }
}

export function Fries({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/fries.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.fries.geometry} material={materials.red}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.fries_1.geometry}
          material={materials.yellow}
          position={[0, 0.16, 0]}
          scale={[1.18, 1.52, 1.18]}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/fries.glb')
