/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_glassWine: THREE.Mesh
    Mesh_glassWine_1: THREE.Mesh
  }
  materials: {
    _defaultMat: THREE.MeshStandardMaterial
    ['[Translucent_Glass_Gray]']: THREE.MeshStandardMaterial
  }
}

export function GlassWine({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/glassWine.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_glassWine.geometry} material={materials._defaultMat} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_glassWine_1.geometry}
        material={materials['[Translucent_Glass_Gray]']}
      />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/glassWine.glb')
