/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_grapes: THREE.Mesh
    Mesh_grapes_1: THREE.Mesh
    Mesh_grapes_2: THREE.Mesh
  }
  materials: {
    purple: THREE.MeshStandardMaterial
    brownDark: THREE.MeshStandardMaterial
    green: THREE.MeshStandardMaterial
  }
}

export function Grapes({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/grapes.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_grapes.geometry} material={materials.purple} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_grapes_1.geometry} material={materials.brownDark} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_grapes_2.geometry} material={materials.green} />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/grapes.glb')
