/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    iceCreamScoopMint: THREE.Mesh
  }
  materials: {
    green: THREE.MeshStandardMaterial
  }
}

export function IceCreamScoopMint({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/iceCreamScoopMint.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.iceCreamScoopMint.geometry}
        material={materials.green}
        scale={[1, 1.19, 1]}
      />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/iceCreamScoopMint.glb')
