/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_lollypop: THREE.Mesh
    Mesh_lollypop_1: THREE.Mesh
    Mesh_lollypop_2: THREE.Mesh
  }
  materials: {
    purpleLight: THREE.MeshStandardMaterial
    brown: THREE.MeshStandardMaterial
    _defaultMat: THREE.MeshStandardMaterial
  }
}

export function Lollypop({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/lollypop.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_lollypop.geometry} material={materials.purpleLight} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_lollypop_1.geometry} material={materials.brown} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_lollypop_2.geometry} material={materials._defaultMat} />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/lollypop.glb')
