/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_makiVegetable: THREE.Mesh
    Mesh_makiVegetable_1: THREE.Mesh
    Mesh_makiVegetable_2: THREE.Mesh
    Mesh_makiVegetable_3: THREE.Mesh
  }
  materials: {
    green: THREE.MeshStandardMaterial
    brownDarkest: THREE.MeshStandardMaterial
    _defaultMat: THREE.MeshStandardMaterial
    yellow: THREE.MeshStandardMaterial
  }
}

export function MakiVegetable({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/makiVegetable.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_makiVegetable.geometry} material={materials.green} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_makiVegetable_1.geometry} material={materials.brownDarkest} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_makiVegetable_2.geometry} material={materials._defaultMat} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_makiVegetable_3.geometry} material={materials.yellow} />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/makiVegetable.glb')
