/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_makiSalmon: THREE.Mesh
    Mesh_makiSalmon_1: THREE.Mesh
    Mesh_makiSalmon_2: THREE.Mesh
  }
  materials: {
    orange: THREE.MeshStandardMaterial
    brownDarkest: THREE.MeshStandardMaterial
    _defaultMat: THREE.MeshStandardMaterial
  }
}

export function MakiSalmon({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/makiSalmon.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_makiSalmon.geometry} material={materials.orange} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_makiSalmon_1.geometry} material={materials.brownDarkest} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_makiSalmon_2.geometry} material={materials._defaultMat} />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/makiSalmon.glb')
