/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_meatCooked: THREE.Mesh
    Mesh_meatCooked_1: THREE.Mesh
    Mesh_meatCooked_2: THREE.Mesh
    Mesh_meatCooked_3: THREE.Mesh
  }
  materials: {
    brownLight: THREE.MeshStandardMaterial
    green: THREE.MeshStandardMaterial
    brown: THREE.MeshStandardMaterial
    brownDark: THREE.MeshStandardMaterial
  }
}

export function MeatCooked({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/meatCooked.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_meatCooked.geometry} material={materials.brownLight} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_meatCooked_1.geometry} material={materials.green} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_meatCooked_2.geometry} material={materials.brown} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_meatCooked_3.geometry} material={materials.brownDark} />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/meatCooked.glb')
