/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_meatRibs: THREE.Mesh
    Mesh_meatRibs_1: THREE.Mesh
  }
  materials: {
    brownDark: THREE.MeshStandardMaterial
    brownLight: THREE.MeshStandardMaterial
  }
}

export function MeatRibs({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/meatRibs.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[0, -Math.PI / 2, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh_meatRibs.geometry} material={materials.brownDark} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_meatRibs_1.geometry} material={materials.brownLight} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/meatRibs.glb')
