/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_mincemeatPie: THREE.Mesh
    Mesh_mincemeatPie_1: THREE.Mesh
    Mesh_mincemeatPie_2: THREE.Mesh
  }
  materials: {
    brown: THREE.MeshStandardMaterial
    brownDark: THREE.MeshStandardMaterial
    _defaultMat: THREE.MeshStandardMaterial
  }
}

export function MincemeatPie({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/mincemeatPie.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_mincemeatPie.geometry} material={materials.brown} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_mincemeatPie_1.geometry} material={materials.brownDark} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_mincemeatPie_2.geometry} material={materials._defaultMat} />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/mincemeatPie.glb')
