/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_mug: THREE.Mesh
    Mesh_mug_1: THREE.Mesh
  }
  materials: {
    brownDark: THREE.MeshStandardMaterial
    greyLight: THREE.MeshStandardMaterial
  }
}

export function Mug({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/mug.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_mug.geometry} material={materials.brownDark} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_mug_1.geometry} material={materials.greyLight} />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/mug.glb')
