/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_musselOpen: THREE.Mesh
    Mesh_musselOpen_1: THREE.Mesh
  }
  materials: {
    brownDarkest: THREE.MeshStandardMaterial
    brownLight: THREE.MeshStandardMaterial
  }
}

export function MusselOpen({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/musselOpen.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[1, 0.72, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh_musselOpen.geometry} material={materials.brownDarkest} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_musselOpen_1.geometry} material={materials.brownLight} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/musselOpen.glb')
