/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
// @ts-ignore
import { GLTF } from 'three-stdlib';
import { brown, lightBrown, purple, white } from '../materials.js';
import { animated } from '@react-spring/three';

type GLTFResult = GLTF & {
	nodes: {
		Mesh_onionHalf: THREE.Mesh;
		Mesh_onionHalf_1: THREE.Mesh;
	};
	materials: {
		brownLight: THREE.MeshStandardMaterial;
		brown: THREE.MeshStandardMaterial;
	};
};

export function OnionHalf({ ...props }: JSX.IntrinsicElements['group']) {
	const group = useRef<THREE.Group>(null);
	const { nodes, materials } = useGLTF(
		'/models/kenney-foods/smoothed/onionHalf.glb',
	) as GLTFResult;
	return (
		<animated.group ref={group} {...props} dispose={null}>
			<mesh
				castShadow
				geometry={nodes.Mesh_onionHalf.geometry}
				material={white}
			/>
			<mesh
				castShadow
				geometry={nodes.Mesh_onionHalf_1.geometry}
				material={purple}
			/>
		</animated.group>
	);
}

useGLTF.preload('/models/kenney-foods/smoothed/onionHalf.glb');
