/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { brown, purple } from "../materials";

type GLTFResult = GLTF & {
  nodes: {
    onion: THREE.Mesh;
  };
  materials: {
    brown: THREE.MeshStandardMaterial;
  };
};

export function Onion({ ...props }: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(
    "/models/kenney-foods/onion.glb"
  ) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow geometry={nodes.onion.geometry} material={purple} />
    </group>
  );
}

useGLTF.preload("/models/kenney-foods/onion.glb");
