/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_panStew: THREE.Mesh
    Mesh_panStew_1: THREE.Mesh
    Mesh_panStew_2: THREE.Mesh
    Mesh_panStew_3: THREE.Mesh
    Mesh_panStew_4: THREE.Mesh
    Mesh_panStew_5: THREE.Mesh
  }
  materials: {
    greyDark: THREE.MeshStandardMaterial
    _defaultMat: THREE.MeshStandardMaterial
    yellow: THREE.MeshStandardMaterial
    brown: THREE.MeshStandardMaterial
    brownDark: THREE.MeshStandardMaterial
    red: THREE.MeshStandardMaterial
  }
}

export function PanStew({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/panStew.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_panStew.geometry} material={materials.greyDark} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_panStew_1.geometry} material={materials._defaultMat} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_panStew_2.geometry} material={materials.yellow} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_panStew_3.geometry} material={materials.brown} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_panStew_4.geometry} material={materials.brownDark} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_panStew_5.geometry} material={materials.red} />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/panStew.glb')
