/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_peanutButter: THREE.Mesh
    Mesh_peanutButter_1: THREE.Mesh
    Mesh_peanutButter_2: THREE.Mesh
  }
  materials: {
    brownDark: THREE.MeshStandardMaterial
    brownLight: THREE.MeshStandardMaterial
    green: THREE.MeshStandardMaterial
  }
}

export function PeanutButter({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/peanutButter.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_peanutButter.geometry} material={materials.brownDark} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_peanutButter_1.geometry} material={materials.brownLight} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_peanutButter_2.geometry} material={materials.green} />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/peanutButter.glb')
