/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_pearHalf: THREE.Mesh
    Mesh_pearHalf_1: THREE.Mesh
    Mesh_pearHalf_2: THREE.Mesh
    Mesh_pearHalf_3: THREE.Mesh
    Mesh_pearHalf_4: THREE.Mesh
  }
  materials: {
    green: THREE.MeshStandardMaterial
    brown: THREE.MeshStandardMaterial
    brownDark: THREE.MeshStandardMaterial
    brownLight: THREE.MeshStandardMaterial
    _defaultMat: THREE.MeshStandardMaterial
  }
}

export function PearHalf({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/pearHalf.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_pearHalf.geometry} material={materials.green} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_pearHalf_1.geometry} material={materials.brown} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_pearHalf_2.geometry} material={materials.brownDark} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_pearHalf_3.geometry} material={materials.brownLight} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_pearHalf_4.geometry} material={materials._defaultMat} />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/pearHalf.glb')
