/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    pizzaBox: THREE.Mesh
    lid: THREE.Mesh
  }
  materials: {
    _defaultMat: THREE.MeshStandardMaterial
  }
}

export function PizzaBox({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/pizzaBox.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.pizzaBox.geometry} material={nodes.pizzaBox.material}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lid.geometry}
          material={nodes.lid.material}
          position={[0.24, 0.49, 0]}
          rotation={[0, 0, 2.09]}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/pizzaBox.glb')
