/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_pizzaCutter: THREE.Mesh
    Mesh_pizzaCutter_1: THREE.Mesh
    Mesh_pizzaCutter_2: THREE.Mesh
    Mesh_pizzaCutter_3: THREE.Mesh
  }
  materials: {
    _defaultMat: THREE.MeshStandardMaterial
    white: THREE.MeshStandardMaterial
    greyLight: THREE.MeshStandardMaterial
    brown: THREE.MeshStandardMaterial
  }
}

export function PizzaCutter({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/pizzaCutter.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_pizzaCutter.geometry} material={materials._defaultMat} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_pizzaCutter_1.geometry} material={materials.white} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_pizzaCutter_2.geometry} material={materials.greyLight} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_pizzaCutter_3.geometry} material={materials.brown} />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/pizzaCutter.glb')
