/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    piece: THREE.Mesh
    piece_1: THREE.Mesh
    piece_2: THREE.Mesh
    piece_3: THREE.Mesh
    piece_4: THREE.Mesh
    piece_5: THREE.Mesh
    piece_6: THREE.Mesh
    piece_7: THREE.Mesh
  }
  materials: {
    _defaultMat: THREE.MeshStandardMaterial
  }
}

export function PlateBroken({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/plateBroken.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.piece.geometry}
        material={nodes.piece.material}
        position={[0.2, 0, 0.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.piece_1.geometry}
        material={nodes.piece_1.material}
        position={[0.22, 0, -0.06]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.piece_2.geometry}
        material={nodes.piece_2.material}
        position={[-0.16, 0, -0.21]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.piece_3.geometry}
        material={nodes.piece_3.material}
        position={[-0.22, 0, -0.06]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.piece_4.geometry}
        material={nodes.piece_4.material}
        position={[-0.2, 0, 0.15]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.piece_5.geometry}
        material={nodes.piece_5.material}
        position={[-0.16, 0, 0.19]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.piece_6.geometry}
        material={nodes.piece_6.material}
        position={[0.12, 0, -0.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.piece_7.geometry}
        material={nodes.piece_7.material}
        position={[0.04, 0, 0.22]}
      />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/plateBroken.glb')
