/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_popsicleChocolate: THREE.Mesh
    Mesh_popsicleChocolate_1: THREE.Mesh
    Mesh_popsicleChocolate_2: THREE.Mesh
  }
  materials: {
    brownLight: THREE.MeshStandardMaterial
    purpleLight: THREE.MeshStandardMaterial
    brownDark: THREE.MeshStandardMaterial
  }
}

export function PopsicleChocolate({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/popsicleChocolate.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_popsicleChocolate.geometry} material={materials.brownLight} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_popsicleChocolate_1.geometry}
        material={materials.purpleLight}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_popsicleChocolate_2.geometry}
        material={materials.brownDark}
      />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/popsicleChocolate.glb')
