/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_riceBall: THREE.Mesh
    Mesh_riceBall_1: THREE.Mesh
  }
  materials: {
    _defaultMat: THREE.MeshStandardMaterial
    brownDarkest: THREE.MeshStandardMaterial
  }
}

export function RiceBall({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/riceBall.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.89}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh_riceBall.geometry} material={materials._defaultMat} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_riceBall_1.geometry} material={materials.brownDarkest} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/riceBall.glb')
