/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_salad: THREE.Mesh
    Mesh_salad_1: THREE.Mesh
    Mesh_salad_2: THREE.Mesh
    Mesh_salad_3: THREE.Mesh
  }
  materials: {
    brown: THREE.MeshStandardMaterial
    green: THREE.MeshStandardMaterial
    red: THREE.MeshStandardMaterial
    greenDark: THREE.MeshStandardMaterial
  }
}

export function Salad({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/salad.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.93}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh_salad.geometry} material={materials.brown} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_salad_1.geometry} material={materials.green} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_salad_2.geometry} material={materials.red} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_salad_3.geometry} material={materials.greenDark} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/salad.glb')
