/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_sandwich: THREE.Mesh
    Mesh_sandwich_1: THREE.Mesh
    Mesh_sandwich_2: THREE.Mesh
    lettuce: THREE.Mesh
    meat: THREE.Mesh
  }
  materials: {
    brown: THREE.MeshStandardMaterial
    brownLight: THREE.MeshStandardMaterial
    brownDark: THREE.MeshStandardMaterial
    green: THREE.MeshStandardMaterial
  }
}

export function Sandwich({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/sandwich.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[0, Math.PI / 2, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh_sandwich.geometry} material={materials.brown} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_sandwich_1.geometry} material={materials.brownLight} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_sandwich_2.geometry}
          material={nodes.Mesh_sandwich_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lettuce.geometry}
          material={materials.green}
          position={[0.01, 0.07, -0.01]}
          scale={[1.12, 1, 1.12]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.meat.geometry}
          material={nodes.meat.material}
          position={[0, 0.08, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/sandwich.glb')
