/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_sodaCan: THREE.Mesh
    Mesh_sodaCan_1: THREE.Mesh
    Mesh_sodaCan_2: THREE.Mesh
    Mesh_sodaCan_3: THREE.Mesh
  }
  materials: {
    greyDark: THREE.MeshStandardMaterial
    greyLight: THREE.MeshStandardMaterial
    red: THREE.MeshStandardMaterial
    brownDarkest: THREE.MeshStandardMaterial
  }
}

export function SodaCan({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/sodaCan.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh_sodaCan.geometry} material={materials.greyDark} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_sodaCan_1.geometry} material={materials.greyLight} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_sodaCan_2.geometry} material={materials.red} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_sodaCan_3.geometry} material={materials.brownDarkest} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/sodaCan.glb')
