/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_layer: THREE.Mesh
    Mesh_layer_1: THREE.Mesh
    Mesh_layer_2: THREE.Mesh
    Mesh_layer_3: THREE.Mesh
    Mesh_layer_4: THREE.Mesh
    Mesh_layer_5: THREE.Mesh
    Mesh_layer_6: THREE.Mesh
    Mesh_layer_7: THREE.Mesh
    Mesh_layer_8: THREE.Mesh
    lid: THREE.Mesh
  }
  materials: {
    brownLight: THREE.MeshStandardMaterial
    brown: THREE.MeshStandardMaterial
    green: THREE.MeshStandardMaterial
  }
}

export function Steamer({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/steamer.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_layer.geometry} material={nodes.Mesh_layer.material} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_layer_1.geometry} material={nodes.Mesh_layer_1.material} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_layer_2.geometry} material={nodes.Mesh_layer_2.material} />
      <group position={[0, 0.18, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh_layer_3.geometry} material={nodes.Mesh_layer_3.material} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_layer_4.geometry} material={nodes.Mesh_layer_4.material} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_layer_5.geometry} material={nodes.Mesh_layer_5.material} />
      </group>
      <group position={[0, 0.36, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh_layer_6.geometry} material={nodes.Mesh_layer_6.material} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_layer_7.geometry} material={nodes.Mesh_layer_7.material} />
        <mesh castShadow receiveShadow geometry={nodes.Mesh_layer_8.geometry} material={nodes.Mesh_layer_8.material} />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lid.geometry}
        material={nodes.lid.material}
        position={[0, 0.52, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/steamer.glb')
