/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_sushiEgg: THREE.Mesh
    Mesh_sushiEgg_1: THREE.Mesh
    Mesh_egg: THREE.Mesh
    Mesh_egg_1: THREE.Mesh
  }
  materials: {
    _defaultMat: THREE.MeshStandardMaterial
    brownDarkest: THREE.MeshStandardMaterial
    yellow: THREE.MeshStandardMaterial
  }
}

export function SushiEgg({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/sushiEgg.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[1, 0.59, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Mesh_sushiEgg.geometry} material={materials._defaultMat} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_sushiEgg_1.geometry}
          material={nodes.Mesh_sushiEgg_1.material}
        />
        <group position={[0, 0.07, 0]} scale={[1, 1.69, 1]}>
          <mesh castShadow receiveShadow geometry={nodes.Mesh_egg.geometry} material={materials.yellow} />
          <mesh castShadow receiveShadow geometry={nodes.Mesh_egg_1.geometry} material={nodes.Mesh_egg_1.material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/sushiEgg.glb')
