/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_taco: THREE.Mesh
    Mesh_taco_1: THREE.Mesh
    Mesh_taco_2: THREE.Mesh
    Mesh_taco_3: THREE.Mesh
    Mesh_taco_4: THREE.Mesh
  }
  materials: {
    brownLight: THREE.MeshStandardMaterial
    yellow: THREE.MeshStandardMaterial
    red: THREE.MeshStandardMaterial
    brownDark: THREE.MeshStandardMaterial
    green: THREE.MeshStandardMaterial
  }
}

export function Taco({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/taco.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_taco.geometry} material={materials.brownLight} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_taco_1.geometry} material={materials.yellow} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_taco_2.geometry} material={materials.red} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_taco_3.geometry} material={materials.brownDark} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_taco_4.geometry} material={materials.green} />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/taco.glb')
