/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_tomatoSlice: THREE.Mesh
    Mesh_tomatoSlice_1: THREE.Mesh
  }
  materials: {
    red: THREE.MeshStandardMaterial
    redLight: THREE.MeshStandardMaterial
  }
}

export function TomatoSlice({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/tomatoSlice.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_tomatoSlice.geometry} material={materials.red} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_tomatoSlice_1.geometry} material={materials.redLight} />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/tomatoSlice.glb')
