/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh_wineWhite: THREE.Mesh
    Mesh_wineWhite_1: THREE.Mesh
    Mesh_wineWhite_2: THREE.Mesh
  }
  materials: {
    brownLight: THREE.MeshStandardMaterial
    green: THREE.MeshStandardMaterial
    brown: THREE.MeshStandardMaterial
  }
}

export function WineWhite({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/kenney-foods/wineWhite.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Mesh_wineWhite.geometry} material={materials.brownLight} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_wineWhite_1.geometry} material={materials.green} />
      <mesh castShadow receiveShadow geometry={nodes.Mesh_wineWhite_2.geometry} material={materials.brown} />
    </group>
  )
}

useGLTF.preload('/models/kenney-foods/wineWhite.glb')
